In [3]:
import pandas as pd
mydataset = {
'Refund': ["Yes", "No", "No", "Yes", "No", "No", "Yes", "No", "No", "No"],
'Marital Status': ["Single", "Married", "Single", "Married", "Divorced", "Married", "Divorced", "Single", "Married", "Single"],
'Taxable Income': [125000, 100000, 70000, 120000, 95000, 60000, 220000, 85000, 75000, 90000],
'Cheat': ["No", "No", "No", "No", "Yes", "No", "No", "Yes", "No", "Yes"]
}
df = pd.DataFrame(mydataset)
print(df)

  Refund Marital Status  Taxable Income Cheat
0    Yes         Single          125000    No
1     No        Married          100000    No
2     No         Single           70000    No
3    Yes        Married          120000    No
4     No       Divorced           95000   Yes
5     No        Married           60000    No
6    Yes       Divorced          220000    No
7     No         Single           85000   Yes
8     No        Married           75000    No
9     No         Single           90000   Yes

In [6]:
print(df.loc[0])
print(df.loc[4])
print(df.loc[7])
print(df.loc[8])

Refund               Yes
Marital Status    Single
Taxable Income    125000
Cheat                 No
Name: 0, dtype: object
Refund                  No
Marital Status    Divorced
Taxable Income       95000
Cheat                  Yes
Name: 4, dtype: object
Refund                No
Marital Status    Single
Taxable Income     85000
Cheat                Yes
Name: 7, dtype: object
Refund                 No
Marital Status    Married
Taxable Income      75000
Cheat                  No
Name: 8, dtype: object

In [11]:
print(df.loc[3:7])

  Refund Marital Status  Taxable Income Cheat
3    Yes        Married          120000    No
4     No       Divorced           95000   Yes
5     No        Married           60000    No
6    Yes       Divorced          220000    No
7     No         Single           85000   Yes

In [21]:
print(df.iloc[4:9, 2:5])

   Taxable Income Cheat
4           95000   Yes
5           60000    No
6          220000    No
7           85000   Yes
8           75000    No

In [22]:
print(df.iloc[:, 1:4])

  Marital Status  Taxable Income Cheat
0         Single          125000    No
1        Married          100000    No
2         Single           70000    No
3        Married          120000    No
4       Divorced           95000   Yes
5        Married           60000    No
6       Divorced          220000    No
7         Single           85000   Yes
8        Married           75000    No
9         Single           90000   Yes

In [23]:
fd = pd.read_csv('Iris.csv')
fd.head()

   Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa

In [24]:
fd.drop(4, axis = 0, inplace = True)
fd.head()

   Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
5   6            5.4           3.9            1.7           0.4  Iris-setosa

In [27]:
fd.drop(columns = ['SepalWidthCm'], axis = 1, inplace=True)
fd.head()

   Id  SepalLengthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1            1.4           0.2  Iris-setosa
1   2            4.9            1.4           0.2  Iris-setosa
2   3            4.7            1.3           0.2  Iris-setosa
3   4            4.6            1.5           0.2  Iris-setosa
5   6            5.4            1.7           0.4  Iris-setosa

In [29]:
mydataset = {
'Employee_ID': [101, 102, 103, 104, 105],
'Name': ["Alice", "Bob", "Charlie", "Diana", "Edward"],
'Department': ["HR", "IT", "IT", "Marketing", "Sales"],
'Age': [29, 34, 41, 28, 38],
'Salary': [50000, 70000, 65000, 55000, 60000],
'Years_of_Experience': [4, 8, 10, 3, 12],
'Joining_Date': ["2020-03-15", "2017-07-19", "2013-06-01", "2021-02-10", "2010-11-25"],
'Gender': ["Female", "Male", "Male", "Female", "Male"],
'Bonus': [5000, 7000, 6000, 4500, 5000],
'Rating': [4.5, 4.0, 3.8, 4.7, 3.5]
}
dd = pd.DataFrame(mydataset)
print(dd)

   Employee_ID     Name Department  Age  Salary  Years_of_Experience  \
0          101    Alice         HR   29   50000                    4
1          102      Bob         IT   34   70000                    8
2          103  Charlie         IT   41   65000                   10
3          104    Diana  Marketing   28   55000                    3
4          105   Edward      Sales   38   60000                   12

  Joining_Date  Gender  Bonus  Rating
0   2020-03-15  Female   5000     4.5
1   2017-07-19    Male   7000     4.0
2   2013-06-01    Male   6000     3.8
3   2021-02-10  Female   4500     4.7
4   2010-11-25    Male   5000     3.5

In [ ]:
import numpy as np
import pandas as pd

print("Shape:", dd.shape)

dd.info()

print(dd.describe())

print("First 5 rows:\n", dd.head(5))
print("\nLast 3 rows:\n", dd.tail(3))

print("Average Salary:", dd["Salary"].mean())
print("Total Bonus:", dd["Bonus"].sum())
print("Youngest Employee Age:", dd["Age"].min())
print("Highest Rating:", dd["Rating"].max())

sorted_dd = dd.sort_values(by="Salary", ascending=False)
print(sorted_dd)

def categorize_rating(rating):
  if rating >= 4.5:
    return "Excellent"
  elif rating >= 4.0:
    return "Good"
  else:
    return "Average"


dd["Performance_Category"] = dd["Rating"].apply(categorize_rating)

print("Missing values in each column:\n", dd.isnull().sum())

dd.rename(columns={"Employee_ID": "ID"}, inplace=True)

exp_gt_5 = dd[dd["Years_of_Experience"] > 5]
print("More than 5 years experience:\n", exp_gt_5)

it_dept = dd[dd["Department"] == "IT"]
print("IT Department employees:\n", it_dept)

dd["Tax"] = dd["Salary"] * 0.10

dd.to_csv("modified_employees.csv", index=False)

Shape: (5, 10)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 10 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Employee_ID          5 non-null      int64
 1   Name                 5 non-null      object
 2   Department           5 non-null      object
 3   Age                  5 non-null      int64
 4   Salary               5 non-null      int64
 5   Years_of_Experience  5 non-null      int64
 6   Joining_Date         5 non-null      object
 7   Gender               5 non-null      object
 8   Bonus                5 non-null      int64
 9   Rating               5 non-null      float64
dtypes: float64(1), int64(5), object(4)
memory usage: 532.0+ bytes
       Employee_ID        Age       Salary  Years_of_Experience   Bonus  \
count     5.000000   5.000000      5.00000             5.000000     5.0
mean    103.000000  34.000000  60000.00000             7.400000  5500.0
std       1.581139   5.612486   7905.69415             3.847077  1000.0
min     101.000000  28.000000  50000.00000             3.000000  4500.0
25%     102.000000  29.000000  55000.00000             4.000000  5000.0
50%     103.000000  34.000000  60000.00000             8.000000  5000.0
75%     104.000000  38.000000  65000.00000            10.000000  6000.0
max     105.000000  41.000000  70000.00000            12.000000  7000.0

         Rating
count  5.000000
mean   4.100000
std    0.494975
min    3.500000
25%    3.800000
50%    4.000000
75%    4.500000
max    4.700000
First 5 rows:
    Employee_ID     Name Department  Age  Salary  Years_of_Experience  \
0          101    Alice         HR   29   50000                    4
1          102      Bob         IT   34   70000                    8
2          103  Charlie         IT   41   65000                   10
3          104    Diana  Marketing   28   55000                    3
4          105   Edward      Sales   38   60000                   12

  Joining_Date  Gender  Bonus  Rating
0   2020-03-15  Female   5000     4.5
1   2017-07-19    Male   7000     4.0
2   2013-06-01    Male   6000     3.8
3   2021-02-10  Female   4500     4.7
4   2010-11-25    Male   5000     3.5

Last 3 rows:
    Employee_ID     Name Department  Age  Salary  Years_of_Experience  \
2          103  Charlie         IT   41   65000                   10
3          104    Diana  Marketing   28   55000                    3
4          105   Edward      Sales   38   60000                   12

  Joining_Date  Gender  Bonus  Rating
2   2013-06-01    Male   6000     3.8
3   2021-02-10  Female   4500     4.7
4   2010-11-25    Male   5000     3.5
Average Salary: 60000.0
Total Bonus: 27500
Youngest Employee Age: 28
Highest Rating: 4.7
   Employee_ID     Name Department  Age  Salary  Years_of_Experience  \
1          102      Bob         IT   34   70000                    8
2          103  Charlie         IT   41   65000                   10
4          105   Edward      Sales   38   60000                   12
3          104    Diana  Marketing   28   55000                    3
0          101    Alice         HR   29   50000                    4

  Joining_Date  Gender  Bonus  Rating
1   2017-07-19    Male   7000     4.0
2   2013-06-01    Male   6000     3.8
4   2010-11-25    Male   5000     3.5
3   2021-02-10  Female   4500     4.7
0   2020-03-15  Female   5000     4.5
Missing values in each column:
 Employee_ID             0
Name                    0
Department              0
Age                     0
Salary                  0
Years_of_Experience     0
Joining_Date            0
Gender                  0
Bonus                   0
Rating                  0
Performance_Category    0
dtype: int64
More than 5 years experience:
     ID     Name Department  Age  Salary  Years_of_Experience Joining_Date  \
1  102      Bob         IT   34   70000                    8   2017-07-19
2  103  Charlie         IT   41   65000                   10   2013-06-01
4  105   Edward      Sales   38   60000                   12   2010-11-25

  Gender  Bonus  Rating Performance_Category
1   Male   7000     4.0                 Good
2   Male   6000     3.8              Average
4   Male   5000     3.5              Average
IT Department employees:
     ID     Name Department  Age  Salary  Years_of_Experience Joining_Date  \
1  102      Bob         IT   34   70000                    8   2017-07-19
2  103  Charlie         IT   41   65000                   10   2013-06-01

  Gender  Bonus  Rating Performance_Category
1   Male   7000     4.0                 Good
2   Male   6000     3.8              Average